[deploy]
startCommand = "python manage.py migrate && gunicorn core.wsgi --bind 0.0.0.0:$PORT"

[[crons]]
schedule = "0 8 * * *"
command = "python manage.py search_jobs && python manage.py send_digest --app-url=https://web-production-6cefe.up.railway.app/queue/"

[[crons]]
schedule = "0 8,18 * * *"
command = "python manage.py sync_gmail"
