# Generated by Django 6.0.5 on 2026-05-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview_scheduled', 'Interview Scheduled'), ('interview_done', 'Interview Done'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=30)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('cv_path', models.CharField(blank=True, max_length=500)),
                ('cover_letter_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField()),
                ('source_url', models.URLField(unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('cv_original_text', models.TextField(blank=True)),
                ('cv_tailored_text', models.TextField(blank=True)),
                ('cv_path', models.CharField(blank=True, max_length=500)),
                ('cover_letter_path', models.CharField(blank=True, max_length=500)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_lead', to='tracker.application')),
            ],
            options={
                'ordering': ['-date_found'],
            },
        ),
    ]
