# Generated by Django 6.0.5 on 2026-05-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField()),
                ('source', models.CharField(choices=[('adzuna', 'Adzuna'), ('rss_indeed', 'Indeed RSS'), ('rss_remote', 'Remote RSS'), ('manual', 'Manual URL')], default='manual', max_length=50)),
                ('source_url', models.URLField(unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ready', 'Ready to Apply'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('cv_original_text', models.TextField(blank=True)),
                ('cv_tailored_text', models.TextField(blank=True)),
                ('cv_path', models.CharField(blank=True, max_length=500)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_lead', to='tracker.application')),
            ],
            options={
                'ordering': ['-date_found'],
            },
        ),
    ]
