# Generated by Django 6.0.5 on 2026-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_add_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblead',
            name='cv_changes',
            field=models.TextField(blank=True),
        ),
    ]
