# Generated by Django 6.0.5 on 2026-06-02 16:13
#
# Rewritten to be idempotent: production already has the cv_changes column
# (it was added manually via SQL before deploy-time migrations were working),
# so a plain AddField crashes with DuplicateColumn there. The field is kept in
# Django's migration state, but the column is only created if it is missing.

from django.db import migrations, models


def _add_column_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing = [
            col.name
            for col in connection.introspection.get_table_description(cursor, 'tracker_joblead')
        ]
    if 'cv_changes' in existing:
        return
    schema_editor.execute(
        "ALTER TABLE tracker_joblead ADD COLUMN cv_changes text NOT NULL DEFAULT ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_add_missing_columns'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='joblead',
                    name='cv_changes',
                    field=models.TextField(blank=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(_add_column_if_missing, migrations.RunPython.noop),
            ],
        ),
    ]
