# Generated by Django 6.0.5 on 2026-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_add_cv_changes_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblead',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
