# Generated by Django 6.0.5 on 2026-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_production_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblead',
            name='cv_tailored_json',
            field=models.TextField(blank=True),
        ),
    ]
