# Generated by Django 6.0.5 on 2026-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_joblead_cv_tailored_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('in_review', 'In Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_done', 'Interview Done'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=30),
        ),
    ]
